name: Build & Push

on:
  push:
    branches: [develop]
    tags: ['v*']
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
      - 'mkdocs.yml'
      - 'site/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    uses: kubeadapt/public-actions/.github/workflows/aws-golang-public-service.yml@main
    with:
      ecr_repository_name: kubeadapt/app/${{ github.event.repository.name }}
      aws_role_to_assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
      ecr_public_alias: w3l5x6r6
    secrets:
      PLATFORM_ASSISTANT_GH_APP_ID: ${{ secrets.PLATFORM_ASSISTANT_GH_APP_ID }}
      PLATFORM_ASSISTANT_GH_APP_PRIVATE_KEY: ${{ secrets.PLATFORM_ASSISTANT_GH_APP_PRIVATE_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
